amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    map_topic: "map"
    set_initial_pose: true
    always_reset_initial_pose: false
    first_map_only: false
    save_pose_rate: 2.0

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "/home/nithin/two_ws/src/two_wheel_bot/maps/my_map.yaml"

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: ["map_server", "amcl"]
