slam_toolbox:
  ros__parameters:
    use_sim_time: true
    slam_toolbox: true
    mode: "mapping"
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint      # or base_link
    scan_topic: /scan
    resolution: 0.05
    publish_tf: true
    tf_buffer_duration: 30.0
    throttle_scans: 1
    map_update_interval: 5.0
    enable_interactive_mode: false
    # (you can add loop-closure params later)
