<?xml version="1.0"?>
<robot name="two_wheeled_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Simple two-wheeled differential robot xacro -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_separation" value="0.3"/>
  <xacro:property name="body_length" value="0.35"/>
  <xacro:property name="body_width" value="0.25"/>
  <xacro:property name="body_height" value="0.10"/>

  <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>

  <!-- base_link (root) -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="3.0"/>
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.03"/>
    </inertial>
  </link>

  <!-- wheel macro -->
  <xacro:macro name="wheel" params="name y">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 ${y} ${wheel_radius}" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 ${y} ${wheel_radius}" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <origin xyz="0 ${y} ${wheel_radius}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- left and right wheels -->
  <xacro:wheel name="left_wheel" y="${wheel_separation/2}"/>
  <xacro:wheel name="right_wheel" y="${-wheel_separation/2}"/>

  <!-- OPTIONAL: Gazebo differential drive plugin (uncomment to use) -->
  <!--
  <gazebo>
    <plugin filename="libgazebo_ros_diff_drive.so" name="gazebo_diff_drive">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>
  -->

</robot>
